require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  Exclude:
    - 'config/'
    - 'db/schema.rb'
    - 'db/migrate/'
    - 'bin/bundle'

Style/Documentation:
  Enabled: false

Security/Open:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Metrics/ClassLength:
  Description: 'Avoid classes longer than 100 lines of code.'
  Max: 100
  Enabled: true

Metrics/ModuleLength:
  Description: 'Avoid modules longer than 100 lines of code.'
  Max: 100
  Enabled: true

Metrics/ParameterLists:
  Description: 'Pass no more than four parameters into a method.'
  Max: 4
  Enabled: true

Metrics/MethodLength:
  Description: 'Avoid methods longer than 10 lines of code.'
  StyleGuide: '<https://github.com/bbatsov/ruby-style-guide#short-methods>'
  Max: 10
  Enabled: true